# nano_gui/ui_windows/basic_stats.py
import os
import pandas as pd
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QLabel, QTableWidget, QTableWidgetItem, QHeaderView
from PyQt6.QtCore import Qt

class BasicStatsWindow(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        
        title = QLabel("Pipeline Read Statistics")
        title.setStyleSheet("font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #3c5457;")
        layout.addWidget(title)
        
        self.table = QTableWidget(0, 4)
        self.table.setHorizontalHeaderLabels(["Barcode", "Total Raw Reads", "Reads After Host Depletion", "Reads After QC"])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        layout.addWidget(self.table)
        
        self.last_mtime = 0

    def update_data(self, config):
        """Instantly updates the table by reading the lightweight read_stats.csv generated by the aggregator."""
        output_dir = config.get('Paths', 'output_directory', fallback=None)
        if not output_dir: return
        
        stats_csv = os.path.join(output_dir, "aggregated_results", "read_stats.csv")
        if not os.path.exists(stats_csv): return
        
        mtime = os.path.getmtime(stats_csv)
        if mtime == self.last_mtime: return
        self.last_mtime = mtime
        
        try:
            df = pd.read_csv(stats_csv)
            self.table.setRowCount(len(df))
            for row, data in df.iterrows():
                
                bc_item = QTableWidgetItem(str(data['barcode']))
                bc_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.table.setItem(row, 0, bc_item)
                
                raw_item = QTableWidgetItem(f"{int(data['raw']):,}")
                raw_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.table.setItem(row, 1, raw_item)
                
                host_item = QTableWidgetItem(f"{int(data['host_depleted']):,}")
                host_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.table.setItem(row, 2, host_item)
                
                qc_item = QTableWidgetItem(f"{int(data['qc']):,}")
                qc_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.table.setItem(row, 3, qc_item)
        except Exception:
            pass