name: nanort-nf-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- Bioinformatics Tools ---
  - fastp=1.0
  - fastplong=0.4
  - minimap2=2.30
  - samtools=1.21
  - bracken=1.0
  - rgi=6.0.5
  - nextflow=26.04.0
  # --- Core & Scientific Python ---
  - python=3.10
  - openjdk=21.0.0
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  # --- GUI & Utility Libraries ---
  - pyqt6
  - pyqtgraph
  - watchdog
  - pip
  - plotly
